import type { Alarm } from './types'

// Активные алармы — real-time защита двигателя.
// Параметры: RPM (overrev), oil-pressure (low), coolant-temp (overheat), oil-temp, boost.
// severity: warn = внимание, violation = контрактный штраф, critical = остановить немедленно.

export const ALARMS: Alarm[] = [
  {
    id: 'ALM-001',
    engineId: 'ENG-001',
    sessionId: 'SES-004',
    parameter: 'rpm',
    severity: 'violation',
    value: 9200,
    limit: 8800,
    unit: 'об/мин',
    action: 'Контрактный штраф — превышение redline',
    message: 'Превышение redline: 9200 при лимите 8800 об/мин',
    acknowledged: false,
    triggeredAt: '2026-05-11T14:23:00Z',
  },
  {
    id: 'ALM-002',
    engineId: 'ENG-007',
    sessionId: 'SES-008',
    parameter: 'oil-pressure',
    severity: 'critical',
    value: 1.2,
    limit: 2.0,
    unit: 'бар',
    action: 'STOP ENGINE — низкое давление масла',
    message: 'Давление масла критически низкое: 1.2 бар при минимуме 2.0',
    acknowledged: false,
    triggeredAt: '2026-05-12T08:45:00Z',
  },
  {
    id: 'ALM-003',
    engineId: 'ENG-004',
    sessionId: 'SES-006',
    parameter: 'coolant-temp',
    severity: 'warn',
    value: 108,
    limit: 100,
    unit: '°C',
    action: 'PIT NOW — перегрев ОЖ',
    message: 'Температура ОЖ превышена: 108°C при лимите 100°C',
    acknowledged: false,
    triggeredAt: '2026-05-11T16:10:00Z',
  },
  {
    id: 'ALM-004',
    engineId: 'ENG-009',
    parameter: 'oil-temp',
    severity: 'warn',
    value: 132,
    limit: 125,
    unit: '°C',
    action: 'Снизить нагрузку — перегрев масла',
    message: 'Температура масла превышена: 132°C при лимите 125°C',
    acknowledged: true,
    triggeredAt: '2026-05-10T11:30:00Z',
  },
  {
    id: 'ALM-005',
    engineId: 'ENG-007',
    sessionId: 'SES-005',
    parameter: 'boost',
    severity: 'violation',
    value: 1.95,
    limit: 1.4,
    unit: 'бар',
    action: 'Контрактный штраф — overboost',
    message: 'Overboost: 1.95 бар при лимите 1.4 бар',
    acknowledged: false,
    triggeredAt: '2026-05-11T09:15:00Z',
  },
  {
    id: 'ALM-006',
    engineId: 'ENG-001',
    parameter: 'rpm',
    severity: 'warn',
    value: 8950,
    limit: 8800,
    unit: 'об/мин',
    action: 'Снизить обороты — приближение к лимиту',
    message: 'Оборачиваемость близка к лимиту: 8950 при redline 8800',
    acknowledged: false,
    triggeredAt: '2026-05-12T07:20:00Z',
  },
]
